module.exports = function (n) {
    const lines = [
        "Only the very oldest people remembered a time when humans could see in colour ",
        "She felt for the lock in the dark ",
        "It was the trip of a lifetime, yet ",
        "She decided to go to her father's grave, to ask his advice ",
        "He waited until her husband was out of the room, then... ",
        "He was going back to a place he'd hoped he would never see again ",
        "She had made a poor job of hiding the damage ",
        "She'd only given in because she was lonely ",
        "Bacon sandwiches always reminded her ",
        "He wanted her job and it would be easy enough to ",
        "She looked around quickly, to see if anything had been taken. ",
        "He hadn't seen the old man since ",
        "There was sadness in her face as she told him he looked a lot like his father ",
        "As the prison gate closed behind him, he saw someone waiting for him ",
        "He was excited to find 150 new emails in his inbox ",
        "Half the names on the list had already been crossed off. ",
        "She took a deep breath and said to her boss - ",
        "There had been many theories about how she had been murdered ",
        "The Ferrari stopped and the tinted window opened to reveal ",
        "She stood out from the crowd because ",
        "He looked at his phone, turned pale, then quickly left the room. She watched him, smiling.",
        "As the sun set on the beaches of goa,",
        "One hand in the sand, ",
        "After 5 years of Quarantine ",
        "As we stood in the moonlight ",
        "This was the first time that he had ",
        "Back in 1992, ",
        "The year is 2026 and ",
        "Can one ever know when and how they die? ",
        "Did you know that ",
        "As the plane started to ascend into madeness "
    ];
    return lines[n];
}